name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu:latest
    stpes:
      - uses: actions/checkout@v2
      - run: docker login -u ${{secret.DOCKER_USERNAME}} -p {{secret.DOCKER_PASSWORD}}
      - run: docker build -t sgaikwad/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true sgaikwad/react-test npm test
